version: '3.8'

services:
  object-detection:
    build:
      context: ./object-detection-service
      dockerfile: Dockerfile
    container_name: object-detection
    ports:
      - "5005:5005"
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
    restart: unless-stopped
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - backend

  song-recommendation:
    build:
      context: ./song-recommendation-service
      dockerfile: Dockerfile
    container_name: song-recommendation
    ports:
      - "5003:5003"
    volumes:
      - ./turkish_song_lyrics.csv:/app/turkish_song_lyrics.csv
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
    restart: unless-stopped
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - backend

  video-creation:
    build:
      context: ./video-creation-service
      dockerfile: Dockerfile
    container_name: video-creation
    ports:
      - "5007:5007"
    volumes:
      - ./shotify-d5ae8-firebase-adminsdk-fbsvc-9d5f8462d8.json:/app/shotify-d5ae8-firebase-adminsdk-fbsvc-9d5f8462d8.json
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
    restart: unless-stopped
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      retries: 5
      start_period: 10s
      timeout: 10s
    networks:
      - backend

networks:
  backend:
    driver: bridge
